services:
  web:
    build: .
    container_name: sc502-app
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sc502-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - ./bd.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sc502-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: appuser
      PMA_PASSWORD: apppass
    ports:
      - "8086:80"

volumes:
  db_data: