services:

  web:
    build: .
    container_name: g5-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - g5-network

  db:
    image: mysql:8.0
    container_name: g5-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - ./bd.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - g5-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: g5-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: appuser
      PMA_PASSWORD: apppass
    ports:
      - "8082:80"   # phpMyAdmin -> http://localhost:8082
    networks:
      - g5-network

volumes:
  db_data:

networks:
  g5-network:
    driver: bridge
